name: login_mysql
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.1.6
  geolocator: ^8.2.1
  geocoding:  ^2.0.4
  http: ^0.13.4
  rounded_loading_button: ^2.0.8
  getwidget: ^2.0.5
  local_auth: ^2.1.0
  shared_preferences: ^2.0.9
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/finger.json


